# Generated by Django 4.0.4 on 2023-11-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_promedio', models.FloatField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('precios', models.FloatField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
                'ordering': ['created'],
            },
        ),
    ]
