# Generated by Django 4.0.4 on 2023-12-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_maximo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_minimo',
            field=models.FloatField(null=True),
        ),
    ]
