# Generated by Django 4.0.4 on 2023-12-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0002_producto_precio_maximo_producto_precio_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precios',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
