# Generated by Django 4.0.4 on 2023-12-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0003_alter_producto_precios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precios',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
