# Generated by Django 4.0.4 on 2024-05-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0005_alter_precios_id_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
