# Generated by Django 4.0.4 on 2024-06-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio_web', '0006_alter_precios_id_alter_producto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precios',
            old_name='precios',
            new_name='lista',
        ),
    ]
